"""add_topic_progress_audio_metadata

Revision ID: fe9ae5741bd9
Revises: 4c56ab169adc
Create Date: 2026-09-28 21:25:12.922583

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9ae5741bd9'
down_revision: Union[str, None] = '4c56ab169adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_progress', sa.Column('audio_position_seconds', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('topic_progress', sa.Column('audio_completed', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('topic_progress', sa.Column('audio_bookmarks', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('topic_progress', sa.Column('audio_playback_speed', sa.Float(), server_default='1.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_progress', 'audio_playback_speed')
    op.drop_column('topic_progress', 'audio_bookmarks')
    op.drop_column('topic_progress', 'audio_completed')
    op.drop_column('topic_progress', 'audio_position_seconds')
    # ### end Alembic commands ###
