"""
Curriculum catalog & educational content definition for GoWow.
Contains complete CDS subjects, lessons, formulas, and verified questions.
Answers and explanations remain strictly on the backend and are never leaked to clients before submission.
"""

from typing import Any, Dict, List, Optional

CURRICULUM_SUBJECTS = [
    {
        "id": "mathematics",
        "examId": "cds",
        "name": "Mathematics",
        "code": "MATH",
        "description": "Build quantitative aptitude, arithmetic precision, and algebraic problem-solving for competitive examinations.",
        "iconName": "Calculator",
        "totalTopicsCount": 3,
        "recommendedTopicId": "percentages",
    },
    {
        "id": "english",
        "examId": "cds",
        "name": "English Language",
        "code": "ENG",
        "description": "Enhance grammatical command, vocabulary breadth, and reading comprehension under timed test conditions.",
        "iconName": "BookOpen",
        "totalTopicsCount": 3,
        "recommendedTopicId": "reading-comprehension",
    },
    {
        "id": "general-knowledge",
        "examId": "cds",
        "name": "General Knowledge",
        "code": "GK",
        "description": "Stay prepared with structured historical milestones, Indian geography, and verified national current affairs.",
        "iconName": "Globe",
        "totalTopicsCount": 3,
        "recommendedTopicId": "current-affairs",
    },
    {
        "id": "reasoning",
        "examId": "cds",
        "name": "Reasoning Ability",
        "code": "REAS",
        "description": "Develop deductive reasoning, logical sequencing, and analytical deduction through structured practice.",
        "iconName": "Brain",
        "totalTopicsCount": 3,
        "recommendedTopicId": "coding-decoding",
    },
]

CURRICULUM_TOPICS = {
    "mathematics": [
        {
            "id": "percentages",
            "subjectId": "mathematics",
            "name": "Percentages",
            "shortDescription": "Core quantitative concept covering conversion, percentage increase/decrease, successive changes, and exam-level word problems.",
            "completedLessons": 6,
            "totalLessons": 10,
            "estimatedMinutes": 15,
            "isRecommended": True,
            "practiceAvailable": True,
            "practiceCount": 15,
            "learningObjectives": [
                "Understand fraction to percentage conversions and vice versa.",
                "Calculate percentage increase and percentage decrease using standard formulas.",
                "Apply successive percentage change rules to competitive examination word problems.",
                "Solve real-world quantitative questions without relying on visual approximations.",
            ],
            "overview": "Percentages represent parts per hundred and form the mathematical foundation for Profit & Loss, Simple & Compound Interest, Data Interpretation, and Ratio analysis.",
            "sections": [
                {
                    "id": "concept-definition",
                    "title": "1. What is a Percentage?",
                    "paragraphs": [
                        "A percentage is a number or ratio expressed as a fraction of 100. It is often denoted using the percent sign '%'. For example, 45% is equal to 45 out of 100, or the fraction 45/100, which reduces to 9/20 or decimal 0.45.",
                        "In competitive exams like the CDS, mastery of standard fraction-to-percentage conversions enables rapid mental calculation without scratch work.",
                    ],
                    "formulas": [
                        {
                            "id": "formula-basic",
                            "visualText": "Percentage = (Part / Whole) × 100",
                            "accessibleText": "Percentage equals Part divided by Whole multiplied by one hundred.",
                            "explanation": "Use this basic relationship whenever you need to find what percent one value is of another total.",
                        },
                        {
                            "id": "formula-part",
                            "visualText": "Part = (Percentage / 100) × Whole",
                            "accessibleText": "Part equals Percentage divided by one hundred multiplied by Whole.",
                            "explanation": "Use this formula to determine the absolute quantity when the percentage and the whole are given.",
                        },
                    ],
                },
                {
                    "id": "percentage-changes",
                    "title": "2. Percentage Increase and Decrease",
                    "paragraphs": [
                        "Percentage change measures the relative difference between an original value and a new value. When the new value exceeds the original, it is an increase. When the new value is less than the original, it is a decrease.",
                        "Always remember that the denominator is the original base value, never the updated value.",
                    ],
                    "formulas": [
                        {
                            "id": "formula-increase",
                            "visualText": "% Increase = [(New Value - Original Value) / Original Value] × 100",
                            "accessibleText": "Percentage Increase equals difference between New Value and Original Value, divided by Original Value, multiplied by one hundred.",
                        },
                        {
                            "id": "formula-decrease",
                            "visualText": "% Decrease = [(Original Value - New Value) / Original Value] × 100",
                            "accessibleText": "Percentage Decrease equals difference between Original Value and New Value, divided by Original Value, multiplied by one hundred.",
                        },
                    ],
                    "examples": [
                        {
                            "id": "ex-1",
                            "question": "If 20 is 25% of a number, what is the number?",
                            "steps": [
                                "Step 1: Let the unknown number be denoted as X.",
                                "Step 2: Translate the statement into an algebraic equation: 25% of X = 20.",
                                "Step 3: Write 25% as the fraction 25/100 (or 1/4): (1/4) × X = 20.",
                                "Step 4: Multiply both sides by 4 to solve for X: X = 20 × 4 = 80.",
                            ],
                            "answer": "80",
                            "explanation": "Because 25% is one-fourth of any quantity, four times 20 gives the original whole value of 80.",
                        },
                    ],
                },
            ],
            "quickRecap": [
                "Percent means per hundred (parts out of 100).",
                "Always divide by the original starting value when calculating percentage increase or decrease.",
                "Multiplying by 0.25 is equivalent to dividing by 4.",
                "A successive increase of 10% followed by 10% is equal to an overall 21% increase, not 20%.",
            ],
            "audioNarrative": "Welcome to the audio walkthrough for Percentages. A percentage is simply a ratio expressed as a fraction of one hundred. For instance, twenty-five percent equals twenty-five over one hundred, or one quarter. In this module, remember two primary rules: First, Percentage equals Part divided by Whole multiplied by one hundred. Second, when finding percentage increase or decrease, the original base value is always placed in the denominator. To practice what you have learned, select the Start Practice button.",
        },
        {
            "id": "algebra",
            "subjectId": "mathematics",
            "name": "Algebra",
            "shortDescription": "Linear equations, quadratic roots, algebraic identities, and system of linear equations for competitive exams.",
            "completedLessons": 4,
            "totalLessons": 8,
            "estimatedMinutes": 20,
            "isRecommended": False,
            "practiceAvailable": True,
            "practiceCount": 12,
            "learningObjectives": [
                "Solve single-variable linear equations and word problems.",
                "Apply quadratic formula and factorization methods to find equation roots.",
                "Use standard algebraic identities like (a + b) squared for fast computation.",
            ],
            "overview": "Algebra forms the core structural backbone for elementary mathematics in defence and civil service testing.",
            "sections": [
                {
                    "id": "algebra-identities",
                    "title": "1. Standard Algebraic Identities",
                    "paragraphs": [
                        "Algebraic identities are equations that remain true for every value substituted for the variables.",
                    ],
                    "formulas": [
                        {
                            "id": "id-1",
                            "visualText": "(a + b)² = a² + 2ab + b²",
                            "accessibleText": "Open parenthesis a plus b close parenthesis squared equals a squared plus two a b plus b squared.",
                        }
                    ],
                }
            ],
            "quickRecap": [
                "Linear equations have exactly one solution.",
                "Quadratic equations have at most two roots.",
            ],
        },
        {
            "id": "geometry",
            "subjectId": "mathematics",
            "name": "Geometry & Mensuration",
            "shortDescription": "Properties of triangles, circles, polygons, and 2D/3D perimeter, area, and volume calculations.",
            "completedLessons": 3,
            "totalLessons": 9,
            "estimatedMinutes": 25,
            "isRecommended": False,
            "practiceAvailable": True,
            "practiceCount": 10,
            "learningObjectives": [
                "Classify triangles and calculate hypotenuse using Pythagoras theorem.",
                "Compute perimeter and area of regular 2D polygons.",
            ],
            "overview": "Geometry tests spatial intuition, angle relationships, and mensuration formulas.",
            "sections": [],
            "quickRecap": ["Sum of angles in any triangle is always 180 degrees."],
        },
    ],
    "english": [
        {
            "id": "reading-comprehension",
            "subjectId": "english",
            "name": "Reading Comprehension",
            "shortDescription": "Techniques for skimming, tone identification, central theme synthesis, and vocabulary-in-context extraction.",
            "completedLessons": 8,
            "totalLessons": 12,
            "estimatedMinutes": 20,
            "isRecommended": True,
            "practiceAvailable": True,
            "practiceCount": 15,
            "learningObjectives": [
                "Identify the central claim and supporting evidence within an argumentative passage.",
                "Infer authorial attitude and tone without relying on external assumptions.",
                "Deduce the meaning of unfamiliar vocabulary items directly from sentence context.",
            ],
            "overview": "Reading comprehension evaluates your ability to process written English accurately, extract nuanced inferences, and answer factual and inferential questions under timed conditions.",
            "sections": [
                {
                    "id": "rc-strategies",
                    "title": "1. Structured Reading Methodology",
                    "paragraphs": [
                        "Rather than reading every word with equal weight, first read the introductory and concluding sentences of each paragraph to identify the passage's structural roadmap.",
                        "Pay close attention to transitional discourse markers like 'however', 'moreover', 'consequently', and 'in contrast', which flag pivots in the author's argument.",
                    ],
                }
            ],
            "quickRecap": [
                "The main idea must cover the entire passage, not just a single paragraph.",
                "Avoid choosing extreme options that use absolute words like 'always' or 'never' unless explicitly justified by the text.",
            ],
            "audioNarrative": "Welcome to Reading Comprehension. In competitive exams, reading comprehension questions test your ability to extract meaning, determine tone, and identify implicit arguments. Read actively by tracking transitions such as however and therefore. Select Start Practice to test your comprehension skills.",
        },
        {
            "id": "grammar",
            "subjectId": "english",
            "name": "Grammar & Sentence Correction",
            "shortDescription": "Master subject-verb agreement, pronoun references, modifiers, prepositions, and active/passive voice conventions.",
            "completedLessons": 10,
            "totalLessons": 12,
            "estimatedMinutes": 18,
            "isRecommended": False,
            "practiceAvailable": True,
            "practiceCount": 20,
            "learningObjectives": [
                "Spot subject-verb agreement discrepancies in complex sentence structures.",
                "Correct misplaced and dangling participle modifiers.",
            ],
            "overview": "Grammar rules govern sentence clarity and syntax across all competitive English papers.",
            "sections": [],
            "quickRecap": ["A singular subject demands a singular verb, regardless of parenthetical phrases in between."],
        },
        {
            "id": "vocabulary",
            "subjectId": "english",
            "name": "Vocabulary & Idioms",
            "shortDescription": "High-frequency root words, synonyms, antonyms, and commonly tested English idioms.",
            "completedLessons": 5,
            "totalLessons": 10,
            "estimatedMinutes": 15,
            "isRecommended": False,
            "practiceAvailable": True,
            "practiceCount": 15,
            "learningObjectives": [
                "Deconstruct unknown words using Latin and Greek prefixes and roots.",
                "Distinguish subtle connotations between closely related synonyms.",
            ],
            "overview": "Vocabulary breadth directly influences performance in sentence completion and cloze tests.",
            "sections": [],
            "quickRecap": ["Context determines whether a word carries a positive, neutral, or pejorative meaning."],
        },
    ],
    "general-knowledge": [
        {
            "id": "history",
            "subjectId": "general-knowledge",
            "name": "Indian History & Freedom Struggle",
            "shortDescription": "Chronology from the 1857 uprising to Independence, social reform movements, and constitutional milestones.",
            "completedLessons": 6,
            "totalLessons": 11,
            "estimatedMinutes": 22,
            "isRecommended": False,
            "practiceAvailable": True,
            "practiceCount": 15,
            "learningObjectives": [
                "Chart the timeline of major non-violent movements led by the Indian National Congress.",
                "Understand key legislative milestones including Government of India Acts 1909, 1919, and 1935.",
            ],
            "overview": "Indian modern history forms a substantial proportion of general knowledge questions in defence and civil examinations.",
            "sections": [],
            "quickRecap": ["The Non-Cooperation Movement was launched in 1920 following the Jallianwala Bagh tragedy."],
        },
        {
            "id": "current-affairs",
            "subjectId": "general-knowledge",
            "name": "Current Affairs & Defence",
            "shortDescription": "National policy initiatives, multilateral summits, joint bilateral military exercises, and international awards.",
            "completedLessons": 4,
            "totalLessons": 9,
            "estimatedMinutes": 15,
            "isRecommended": True,
            "practiceAvailable": True,
            "practiceCount": 20,
            "learningObjectives": [
                "Recall key joint defence exercises conducted by Indian Armed Forces with partner nations.",
                "Stay informed on prominent scientific achievements and national infrastructure projects.",
            ],
            "overview": "Current affairs questions test contemporary awareness across national security, governance, and science.",
            "sections": [],
            "quickRecap": ["Bilateral military exercises such as Mitra Shakti and Surya Kiran are recurring test items."],
            "audioNarrative": "Welcome to Current Affairs and Defence. This section covers key developments in national governance, defense acquisitions, and international treaties. Select Start Practice to test your knowledge on current affairs.",
        },
        {
            "id": "geography",
            "subjectId": "general-knowledge",
            "name": "Physical & Indian Geography",
            "shortDescription": "River drainage basins, monsoon wind systems, soil classifications, and mineral resources.",
            "completedLessons": 4,
            "totalLessons": 8,
            "estimatedMinutes": 20,
            "isRecommended": False,
            "practiceAvailable": True,
            "practiceCount": 12,
            "learningObjectives": [
                "Trace the origins and tributaries of Himalayan and Peninsular river networks.",
                "Understand the mechanics of South-West and North-East monsoon mechanisms.",
            ],
            "overview": "Geography questions evaluate physical terrain analysis and resource distribution in India.",
            "sections": [],
            "quickRecap": ["The Western Ghats act as a major orographic precipitation barrier during the South-West monsoon."],
        },
    ],
    "reasoning": [
        {
            "id": "coding-decoding",
            "subjectId": "reasoning",
            "name": "Coding & Decoding",
            "shortDescription": "Letter shifting patterns, reverse alphabet pairs, numerical substitutions, and matrix coding problems.",
            "completedLessons": 7,
            "totalLessons": 10,
            "estimatedMinutes": 15,
            "isRecommended": True,
            "practiceAvailable": True,
            "practiceCount": 15,
            "learningObjectives": [
                "Quickly map alphabetic letter ranks from 1 to 26 and their reverse complements (sum equals 27).",
                "Identify shift rules such as alternating additions and subtractions.",
                "Solve conditional symbol substitution puzzles.",
            ],
            "overview": "Coding and decoding evaluates logical substitution rules and sequential pattern tracking.",
            "sections": [
                {
                    "id": "cd-logic",
                    "title": "1. Alphabetical Positioning & Opposite Pairs",
                    "paragraphs": [
                        "Each English letter corresponds to a unique positional number: A = 1, B = 2, up to Z = 26. Useful mnemonic rule is EJOTY, standing for 5, 10, 15, 20, and 25.",
                        "Opposite pairs are letters whose positional ranks sum to 27: A with Z (1+26=27), B with Y (2+25=27), and M with N (13+14=27).",
                    ],
                }
            ],
            "quickRecap": [
                "Use EJOTY (5, 10, 15, 20, 25) to immediately locate letter numbers.",
                "Opposite letters always sum to 27.",
            ],
            "audioNarrative": "Welcome to Coding and Decoding. In this reasoning topic, you will decipher alphabetical shifts and numerical substitutions. Remember that opposite pairs of letters always sum to twenty-seven. Select Start Practice to test your pattern identification skills.",
        },
        {
            "id": "series",
            "subjectId": "reasoning",
            "name": "Number & Alphabet Series",
            "shortDescription": "Arithmetic, geometric, alternating, and prime-based series progression rules.",
            "completedLessons": 5,
            "totalLessons": 8,
            "estimatedMinutes": 18,
            "isRecommended": False,
            "practiceAvailable": True,
            "practiceCount": 15,
            "learningObjectives": [
                "Identify second-order difference patterns in complex number sequences.",
                "Detect alternating multi-tier sequences.",
            ],
            "overview": "Number series questions measure inductive reasoning and mathematical sequence recognition.",
            "sections": [],
            "quickRecap": ["When in doubt, calculate the differences between adjacent numbers to find second-tier patterns."],
        },
        {
            "id": "analogy",
            "subjectId": "reasoning",
            "name": "Analogy & Classification",
            "shortDescription": "Verbal relationships, word associations, number relationships, and odd-one-out puzzles.",
            "completedLessons": 8,
            "totalLessons": 10,
            "estimatedMinutes": 12,
            "isRecommended": False,
            "practiceAvailable": True,
            "practiceCount": 10,
            "learningObjectives": [
                "Identify the exact functional or taxonomic relationship between word pairs.",
                "Apply proportional logic to mathematical number pairs.",
            ],
            "overview": "Analogies test proportional relationship deduction across verbal and numeric domains.",
            "sections": [],
            "quickRecap": ["First identify whether the relationship is cause-and-effect, part-to-whole, or functional purpose."],
        },
    ],
}

PRACTICE_QUESTIONS_MASTER = [
    {
        "id": "math-perc-01",
        "subjectId": "mathematics",
        "subjectName": "Mathematics",
        "topicId": "percentages",
        "topicName": "Percentages",
        "type": "single_choice",
        "difficulty": "easy",
        "questionText": "If 20 is 25% of a number, what is the number?",
        "options": [
            {"id": "A", "label": "A", "text": "50"},
            {"id": "B", "label": "B", "text": "80"},
            {"id": "C", "label": "C", "text": "100"},
            {"id": "D", "label": "D", "text": "120"},
        ],
        "correctOptionIds": ["B"],
        "explanation": "25% of a number equals 1/4 of that number. If 1/4 of X = 20, then X = 20 × 4 = 80. Therefore, the number is 80.",
        "hint": "Convert 25% to its fraction equivalent of 1/4.",
        "audioDescription": "Question 1. If 20 is 25 percent of a number, what is the number? Option A: 50. Option B: 80. Option C: 100. Option D: 120.",
    },
    {
        "id": "math-perc-02",
        "subjectId": "mathematics",
        "subjectName": "Mathematics",
        "topicId": "percentages",
        "topicName": "Percentages",
        "type": "single_choice",
        "difficulty": "easy",
        "questionText": "What is 15% of 240?",
        "options": [
            {"id": "A", "label": "A", "text": "32"},
            {"id": "B", "label": "B", "text": "36"},
            {"id": "C", "label": "C", "text": "40"},
            {"id": "D", "label": "D", "text": "42"},
        ],
        "correctOptionIds": ["B"],
        "explanation": "10% of 240 is 24. 5% of 240 is half of 24, which is 12. Summing 10% and 5% gives 24 + 12 = 36.",
        "hint": "Break 15% into 10% plus 5%.",
        "audioDescription": "Question 2. What is 15 percent of 240? Option A: 32. Option B: 36. Option C: 40. Option D: 42.",
    },
    {
        "id": "math-perc-03",
        "subjectId": "mathematics",
        "subjectName": "Mathematics",
        "topicId": "percentages",
        "topicName": "Percentages",
        "type": "single_choice",
        "difficulty": "medium",
        "questionText": "The price of an article increased from ₹800 to ₹1,000. What is the percentage increase?",
        "options": [
            {"id": "A", "label": "A", "text": "20%"},
            {"id": "B", "label": "B", "text": "25%"},
            {"id": "C", "label": "C", "text": "30%"},
            {"id": "D", "label": "D", "text": "12.5%"},
        ],
        "correctOptionIds": ["B"],
        "explanation": "Absolute increase = ₹1000 - ₹800 = ₹200. Percentage increase = (Increase / Original Base) × 100 = (200 / 800) × 100 = 1/4 × 100 = 25%.",
        "hint": "Always divide by the original starting price of ₹800, not the new price.",
        "audioDescription": "Question 3. The price of an article increased from 800 rupees to 1000 rupees. What is the percentage increase? Option A: 20 percent. Option B: 25 percent. Option C: 30 percent. Option D: 12.5 percent.",
    },
    {
        "id": "math-perc-04",
        "subjectId": "mathematics",
        "subjectName": "Mathematics",
        "topicId": "percentages",
        "topicName": "Percentages",
        "type": "true_false",
        "difficulty": "easy",
        "questionText": "True or False: A 10% increase followed by a 10% decrease returns a quantity to its original initial value.",
        "options": [
            {"id": "A", "label": "A", "text": "True"},
            {"id": "B", "label": "B", "text": "False"},
        ],
        "correctOptionIds": ["B"],
        "explanation": "False. Let original = 100. A 10% increase makes it 110. A 10% decrease of 110 reduces it by 11 to 99, resulting in a net 1% loss.",
        "audioDescription": "Question 4. True or False: A 10 percent increase followed by a 10 percent decrease returns a quantity to its original initial value? Option A: True. Option B: False.",
    },
    {
        "id": "math-perc-05",
        "subjectId": "mathematics",
        "subjectName": "Mathematics",
        "topicId": "percentages",
        "topicName": "Percentages",
        "type": "single_choice",
        "difficulty": "hard",
        "questionText": "In an examination, 65% of candidates passed in English, 60% passed in Mathematics, and 40% passed in both. What percentage of candidates failed in both subjects?",
        "options": [
            {"id": "A", "label": "A", "text": "15%"},
            {"id": "B", "label": "B", "text": "20%"},
            {"id": "C", "label": "C", "text": "25%"},
            {"id": "D", "label": "D", "text": "35%"},
        ],
        "correctOptionIds": ["A"],
        "explanation": "Using set theory: Passed in at least one subject = P(E) + P(M) - P(E ∩ M) = 65% + 60% - 40% = 85%. Therefore, candidates who failed in both = 100% - 85% = 15%.",
        "hint": "Add the single subject passes and subtract the intersection.",
        "audioDescription": "Question 5. In an examination, 65 percent passed in English, 60 percent passed in Mathematics, and 40 percent passed in both. What percentage failed in both subjects? Option A: 15 percent. Option B: 20 percent. Option C: 25 percent. Option D: 35 percent.",
    },
    {
        "id": "reas-code-01",
        "subjectId": "reasoning",
        "subjectName": "Reasoning Ability",
        "topicId": "coding-decoding",
        "topicName": "Coding & Decoding",
        "type": "single_choice",
        "difficulty": "easy",
        "questionText": "If 'DELHI' is coded as 'EDMIJ', how is 'MUMBAI' coded following the same logic?",
        "options": [
            {"id": "A", "label": "A", "text": "NVNCBJ"},
            {"id": "B", "label": "B", "text": "NVMCBJ"},
            {"id": "C", "label": "C", "text": "LTLAZH"},
            {"id": "D", "label": "D", "text": "OWNCDK"},
        ],
        "correctOptionIds": ["A"],
        "explanation": "Every letter is shifted forward by 1 rank: M(+1)=N, U(+1)=V, M(+1)=N, B(+1)=C, A(+1)=B, I(+1)=J giving NVNCBJ.",
        "audioDescription": "Question 6. If DELHI is coded as EDMIJ, how is MUMBAI coded? Option A: NVNCBJ. Option B: NVMCBJ. Option C: LTLAZH. Option D: OWNCDK.",
    },
    {
        "id": "reas-code-02",
        "subjectId": "reasoning",
        "subjectName": "Reasoning Ability",
        "topicId": "coding-decoding",
        "topicName": "Coding & Decoding",
        "type": "single_choice",
        "difficulty": "medium",
        "questionText": "In a certain code language, 'CAT' is coded as 24 and 'DOG' is coded as 26. What is the code for 'PIG'?",
        "options": [
            {"id": "A", "label": "A", "text": "32"},
            {"id": "B", "label": "B", "text": "30"},
            {"id": "C", "label": "C", "text": "28"},
            {"id": "D", "label": "D", "text": "34"},
        ],
        "correctOptionIds": ["A"],
        "explanation": "Sum of alphabetical positions: C(3) + A(1) + T(20) = 24. D(4) + O(15) + G(7) = 26. For PIG: P(16) + I(9) + G(7) = 32.",
        "audioDescription": "Question 7. In a certain code language, CAT is coded as 24 and DOG is coded as 26. What is the code for PIG? Option A: 32. Option B: 30. Option C: 28. Option D: 34.",
    },
    {
        "id": "eng-gram-01",
        "subjectId": "english",
        "subjectName": "English Language",
        "topicId": "grammar",
        "topicName": "Grammar & Sentence Correction",
        "type": "single_choice",
        "difficulty": "easy",
        "questionText": "Identify the sentence with correct subject-verb agreement:",
        "options": [
            {"id": "A", "label": "A", "text": "The group of students were cheering loudly in the auditorium."},
            {"id": "B", "label": "B", "text": "The group of students was cheering loudly in the auditorium."},
            {"id": "C", "label": "C", "text": "The group of students are cheering loudly in the auditorium."},
            {"id": "D", "label": "D", "text": "The group of students have cheered loudly in the auditorium."},
        ],
        "correctOptionIds": ["B"],
        "explanation": "The subject is the collective singular noun 'The group', not 'students'. Singular subject requires the singular auxiliary verb 'was'.",
        "audioDescription": "Question 8. Identify the sentence with correct subject-verb agreement. Option A: were cheering. Option B: was cheering. Option C: are cheering. Option D: have cheered.",
    },
    {
        "id": "eng-rc-01",
        "subjectId": "english",
        "subjectName": "English Language",
        "topicId": "reading-comprehension",
        "topicName": "Reading Comprehension",
        "type": "single_choice",
        "difficulty": "medium",
        "questionText": "When an author uses the transitional phrase 'on the contrary', what argumentative direction is signaled?",
        "options": [
            {"id": "A", "label": "A", "text": "Reinforcement of a previously stated premise"},
            {"id": "B", "label": "B", "text": "An emphatic reversal or counter-argument"},
            {"id": "C", "label": "C", "text": "A sequential chronological timeline"},
            {"id": "D", "label": "D", "text": "An introductory rhetorical question"},
        ],
        "correctOptionIds": ["B"],
        "explanation": "'On the contrary' is used to strongly contradict a previous assertion and present the opposing reality.",
        "audioDescription": "Question 9. When an author uses the phrase on the contrary, what argumentative direction is signaled? Option A: Reinforcement. Option B: An emphatic reversal. Option C: Chronological timeline. Option D: Rhetorical question.",
    },
    {
        "id": "gk-curr-01",
        "subjectId": "general-knowledge",
        "subjectName": "General Knowledge",
        "topicId": "current-affairs",
        "topicName": "Current Affairs & Defence",
        "type": "single_choice",
        "difficulty": "medium",
        "questionText": "The bilateral joint military exercise 'MITRA SHAKTI' is conducted between the armed forces of India and which neighboring country?",
        "options": [
            {"id": "A", "label": "A", "text": "Nepal"},
            {"id": "B", "label": "B", "text": "Sri Lanka"},
            {"id": "C", "label": "C", "text": "Bangladesh"},
            {"id": "D", "label": "D", "text": "Maldives"},
        ],
        "correctOptionIds": ["B"],
        "explanation": "Exercise Mitra Shakti is an annual bilateral military exercise conducted jointly between the Indian Army and the Sri Lanka Army.",
        "audioDescription": "Question 10. The bilateral joint military exercise MITRA SHAKTI is conducted between India and which country? Option A: Nepal. Option B: Sri Lanka. Option C: Bangladesh. Option D: Maldives.",
    },
]

MOCK_TESTS_MASTER = [
    {
        "id": "cds-full-mock-01",
        "title": "CDS Full Practice Examination — 01",
        "examName": "CDS (Combined Defence Services)",
        "examCode": "UPSC-CDS",
        "description": "Comprehensive CDS-style practice mock covering English Language, General Knowledge, and Elementary Mathematics under standard timing.",
        "totalQuestions": 6,
        "durationMinutes": 45,
        "difficulty": "medium",
        "status": "not_started",
        "isRecommended": True,
        "markingScheme": {
            "correctMarks": 1.0,
            "incorrectPenalty": 0.33,
            "unansweredMarks": 0.0,
        },
        "instructionsSummary": [
            "This is a timed practice simulation designed to reflect competitive CDS testing parameters.",
            "Negative marking is applied: +1 mark for correct answers, -0.33 mark for incorrect attempts.",
            "Unanswered or skipped questions carry zero penalty.",
            "You can freely navigate between sections using the Section tabs.",
            "You can Mark questions for Review and return to them at any point before final submission.",
        ],
        "accessibilityHighlights": {
            "keyboard": "Full keyboard navigation supported (Tab, Shift+Tab, Arrow keys, Enter, Space).",
            "screenReader": "Designed for screen-reader compatibility with semantic landmark hierarchy.",
            "audio": "Audio assistance available for question prompts and choices per your settings.",
            "visual": "High contrast outlines, dark mode compatibility, and scalable typography supported.",
        },
        "sections": [
            {
                "id": "sec-english",
                "name": "English Language",
                "code": "ENG",
                "description": "Grammar, vocabulary, and reading comprehension.",
                "totalQuestions": 2,
                "questions": [
                    {
                        "id": "cds-eng-01",
                        "sectionId": "sec-english",
                        "questionNumber": 1,
                        "text": "Choose the word that is most nearly opposite in meaning to 'CANDID':",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "options": [
                            {"id": "A", "label": "A", "text": "Outspoken"},
                            {"id": "B", "label": "B", "text": "Secretive"},
                            {"id": "C", "label": "C", "text": "Blunt"},
                            {"id": "D", "label": "D", "text": "Sincere"},
                        ],
                        "correctOptionIds": ["B"],
                        "explanation": "'Candid' means truthful and straightforward. Its antonym is 'secretive' or 'deceptive'.",
                        "audioText": "Question 1. Choose the word that is most nearly opposite in meaning to CANDID.",
                    },
                    {
                        "id": "cds-eng-02",
                        "sectionId": "sec-english",
                        "questionNumber": 2,
                        "text": "Select the option that correctly rectifies the grammatical error: 'Neither the manager nor the employees was present at the briefing.'",
                        "type": "single_choice",
                        "difficulty": "medium",
                        "options": [
                            {"id": "A", "label": "A", "text": "Neither the manager nor the employees were present at the briefing."},
                            {"id": "B", "label": "B", "text": "Neither the manager or the employees was present at the briefing."},
                            {"id": "C", "label": "C", "text": "Neither the manager nor the employee was present at the briefing."},
                            {"id": "D", "label": "D", "text": "No correction required; the sentence is correct."},
                        ],
                        "correctOptionIds": ["A"],
                        "explanation": "When two subjects are joined by 'neither... nor', the verb agrees with the closer subject ('employees', plural), so 'were present' is required.",
                        "audioText": "Question 2. Select the option that correctly rectifies the grammatical error.",
                    },
                ],
            },
            {
                "id": "sec-math",
                "name": "Elementary Mathematics",
                "code": "MATH",
                "description": "Arithmetic, algebra, and quantitative deduction.",
                "totalQuestions": 2,
                "questions": [
                    {
                        "id": "cds-math-01",
                        "sectionId": "sec-math",
                        "questionNumber": 3,
                        "text": "If 20 is 25% of a number, what is the number?",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "formula": {
                            "visualText": "25% of X = 20  =>  (1/4)X = 20",
                            "accessibleText": "twenty-five percent of X equals twenty, which implies one fourth of X equals twenty",
                        },
                        "options": [
                            {"id": "A", "label": "A", "text": "50"},
                            {"id": "B", "label": "B", "text": "80"},
                            {"id": "C", "label": "C", "text": "100"},
                            {"id": "D", "label": "D", "text": "120"},
                        ],
                        "correctOptionIds": ["B"],
                        "explanation": "25% of X = 20 implies (1/4)X = 20, hence X = 80.",
                        "audioText": "Question 3. If 20 is 25 percent of a number, what is the number?",
                    },
                    {
                        "id": "cds-math-02",
                        "sectionId": "sec-math",
                        "questionNumber": 4,
                        "text": "What is 15% of 240?",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "options": [
                            {"id": "A", "label": "A", "text": "32"},
                            {"id": "B", "label": "B", "text": "36"},
                            {"id": "C", "label": "C", "text": "40"},
                            {"id": "D", "label": "D", "text": "42"},
                        ],
                        "correctOptionIds": ["B"],
                        "explanation": "10% of 240 is 24. 5% is 12. Sum is 36.",
                        "audioText": "Question 4. What is 15 percent of 240?",
                    },
                ],
            },
            {
                "id": "sec-gk",
                "name": "General Knowledge",
                "code": "GK",
                "description": "Current affairs, modern history, and defense.",
                "totalQuestions": 2,
                "questions": [
                    {
                        "id": "cds-gk-01",
                        "sectionId": "sec-gk",
                        "questionNumber": 5,
                        "text": "The bilateral joint military exercise 'MITRA SHAKTI' is conducted between India and which country?",
                        "type": "single_choice",
                        "difficulty": "medium",
                        "options": [
                            {"id": "A", "label": "A", "text": "Nepal"},
                            {"id": "B", "label": "B", "text": "Sri Lanka"},
                            {"id": "C", "label": "C", "text": "Bangladesh"},
                            {"id": "D", "label": "D", "text": "Maldives"},
                        ],
                        "correctOptionIds": ["B"],
                        "explanation": "Exercise Mitra Shakti is conducted between Indian Army and Sri Lanka Army.",
                        "audioText": "Question 5. The bilateral military exercise MITRA SHAKTI is conducted between India and which country?",
                    },
                    {
                        "id": "cds-gk-02",
                        "sectionId": "sec-gk",
                        "questionNumber": 6,
                        "text": "In a certain code language, CAT is coded as 24 and DOG is coded as 26. What is the code for PIG?",
                        "type": "single_choice",
                        "difficulty": "medium",
                        "options": [
                            {"id": "A", "label": "A", "text": "32"},
                            {"id": "B", "label": "B", "text": "30"},
                            {"id": "C", "label": "C", "text": "28"},
                            {"id": "D", "label": "D", "text": "34"},
                        ],
                        "correctOptionIds": ["A"],
                        "explanation": "Sum of ranks: P(16) + I(9) + G(7) = 32.",
                        "audioText": "Question 6. What is the code for PIG?",
                    },
                ],
            },
        ],
    },
    {
        "id": "mock-math-01",
        "title": "Elementary Mathematics Subject Mock Test",
        "examName": "CDS (Combined Defence Services)",
        "examCode": "CDS-MATH",
        "description": "Dedicated subject mock test covering Arithmetic, Percentages, Algebra, and Geometry with accessible formulas.",
        "totalQuestions": 6,
        "durationMinutes": 30,
        "difficulty": "medium",
        "status": "not_started",
        "isRecommended": True,
        "markingScheme": {
            "correctMarks": 1.0,
            "incorrectPenalty": 0.33,
            "unansweredMarks": 0.0,
        },
        "instructionsSummary": [
            "Mathematics subject-wise drill covering Arithmetic, Algebra, and Geometry.",
            "Marking Scheme: +1 for correct, -0.33 penalty for incorrect answers.",
            "Accessible formula narration enabled for all mathematical notation.",
        ],
        "accessibilityHighlights": {
            "keyboard": "Full keyboard navigation supported.",
            "screenReader": "Formula spoken text enabled for screen readers.",
            "audio": "Audio description available.",
            "visual": "High contrast and scalable typography supported.",
        },
        "sections": [
            {
                "id": "sec-math-arith",
                "name": "Arithmetic & Percentages",
                "code": "ARITH",
                "description": "Percentages, ratios, and commercial arithmetic.",
                "totalQuestions": 2,
                "questions": [
                    {
                        "id": "math-m-01",
                        "sectionId": "sec-math-arith",
                        "questionNumber": 1,
                        "text": "If 20 is 25% of a number, what is the number?",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "formula": {
                            "visualText": "25% of X = 20  =>  (1/4)X = 20",
                            "accessibleText": "twenty-five percent of X equals twenty, which implies one fourth of X equals twenty",
                        },
                        "options": [
                            {"id": "A", "label": "A", "text": "50"},
                            {"id": "B", "label": "B", "text": "80"},
                            {"id": "C", "label": "C", "text": "100"},
                            {"id": "D", "label": "D", "text": "120"},
                        ],
                        "correctOptionIds": ["B"],
                        "explanation": "25% of X = 20 means (1/4)X = 20, hence X = 80.",
                        "audioText": "Question 1. If 20 is 25 percent of a number, what is the number?",
                    },
                    {
                        "id": "math-m-02",
                        "sectionId": "sec-math-arith",
                        "questionNumber": 2,
                        "text": "The price of an article increased from ₹800 to ₹1,000. What is the percentage increase?",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "formula": {
                            "visualText": "% Increase = [(New - Original) / Original] × 100",
                            "accessibleText": "percentage increase equals new price minus original price divided by original price multiplied by one hundred",
                        },
                        "options": [
                            {"id": "A", "label": "A", "text": "20%"},
                            {"id": "B", "label": "B", "text": "25%"},
                            {"id": "C", "label": "C", "text": "30%"},
                            {"id": "D", "label": "D", "text": "12.5%"},
                        ],
                        "correctOptionIds": ["B"],
                        "explanation": "Absolute increase = 1000 - 800 = 200. Percentage increase = (200 / 800) * 100 = 25%.",
                        "audioText": "Question 2. The price of an article increased from 800 rupees to 1000 rupees. What is the percentage increase?",
                    },
                ],
            },
            {
                "id": "sec-math-alg",
                "name": "Algebra & Equations",
                "code": "ALG",
                "description": "Quadratic roots and algebraic identities.",
                "totalQuestions": 2,
                "questions": [
                    {
                        "id": "math-m-03",
                        "sectionId": "sec-math-alg",
                        "questionNumber": 3,
                        "text": "If x² - 5x + 6 = 0, what are the roots of the quadratic equation?",
                        "type": "single_choice",
                        "difficulty": "medium",
                        "formula": {
                            "visualText": "x² - 5x + 6 = (x - 2)(x - 3) = 0",
                            "accessibleText": "x squared minus 5x plus 6 equals open parenthesis x minus 2 close parenthesis times open parenthesis x minus 3 close parenthesis equals zero",
                        },
                        "options": [
                            {"id": "A", "label": "A", "text": "2 and 3"},
                            {"id": "B", "label": "B", "text": "-2 and -3"},
                            {"id": "C", "label": "C", "text": "1 and 6"},
                            {"id": "D", "label": "D", "text": "-1 and -6"},
                        ],
                        "correctOptionIds": ["A"],
                        "explanation": "Factorizing x² - 5x + 6 = 0 gives (x - 2)(x - 3) = 0, so x = 2 or x = 3.",
                        "audioText": "Question 3. If x squared minus 5x plus 6 equals 0, what are the roots of the equation?",
                    },
                    {
                        "id": "math-m-04",
                        "sectionId": "sec-math-alg",
                        "questionNumber": 4,
                        "text": "What is the standard algebraic expansion of (a - b)²?",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "formula": {
                            "visualText": "(a - b)² = a² - 2ab + b²",
                            "accessibleText": "open parenthesis a minus b close parenthesis squared equals a squared minus 2 a b plus b squared",
                        },
                        "options": [
                            {"id": "A", "label": "A", "text": "a² - 2ab + b²"},
                            {"id": "B", "label": "B", "text": "a² + 2ab + b²"},
                            {"id": "C", "label": "C", "text": "a² - b²"},
                            {"id": "D", "label": "D", "text": "a² + b²"},
                        ],
                        "correctOptionIds": ["A"],
                        "explanation": "The standard identity is (a - b)² = a² - 2ab + b².",
                        "audioText": "Question 4. What is the standard algebraic expansion of open parenthesis a minus b close parenthesis squared?",
                    },
                ],
            },
            {
                "id": "sec-math-geom",
                "name": "Geometry & Mensuration",
                "code": "GEOM",
                "description": "Properties of triangles and circle mensuration.",
                "totalQuestions": 2,
                "questions": [
                    {
                        "id": "math-m-05",
                        "sectionId": "sec-math-geom",
                        "questionNumber": 5,
                        "text": "The sum of all three interior angles in any planar triangle is equal to:",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "options": [
                            {"id": "A", "label": "A", "text": "90°"},
                            {"id": "B", "label": "B", "text": "180°"},
                            {"id": "C", "label": "C", "text": "270°"},
                            {"id": "D", "label": "D", "text": "360°"},
                        ],
                        "correctOptionIds": ["B"],
                        "explanation": "The sum of the interior angles of any planar triangle is always 180 degrees.",
                        "audioText": "Question 5. The sum of all three interior angles in any planar triangle is equal to what?",
                    },
                    {
                        "id": "math-m-06",
                        "sectionId": "sec-math-geom",
                        "questionNumber": 6,
                        "text": "What is the area of a circle with a radius of 7 cm? (Take π = 22/7)",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "formula": {
                            "visualText": "Area = πr² = (22/7) × 7 × 7 = 154 cm²",
                            "accessibleText": "Area equals pi r squared equals twenty-two over seven times seven times seven equals 154 square centimeters",
                        },
                        "options": [
                            {"id": "A", "label": "A", "text": "154 cm²"},
                            {"id": "B", "label": "B", "text": "44 cm²"},
                            {"id": "C", "label": "C", "text": "88 cm²"},
                            {"id": "D", "label": "D", "text": "140 cm²"},
                        ],
                        "correctOptionIds": ["A"],
                        "explanation": "Area = πr² = (22/7) * 7 * 7 = 154 cm².",
                        "audioText": "Question 6. What is the area of a circle with a radius of 7 centimeters taking pi as 22 over 7?",
                    },
                ],
            },
        ],
    },
    {
        "id": "mock-eng-01",
        "title": "English Language & Comprehension Mock Test",
        "examName": "CDS (Combined Defence Services)",
        "examCode": "CDS-ENG",
        "description": "Dedicated English mock test evaluating Grammar rules, Vocabulary antonyms/synonyms, and Reading Comprehension.",
        "totalQuestions": 6,
        "durationMinutes": 30,
        "difficulty": "medium",
        "status": "not_started",
        "isRecommended": True,
        "markingScheme": {
            "correctMarks": 1.0,
            "incorrectPenalty": 0.33,
            "unansweredMarks": 0.0,
        },
        "instructionsSummary": [
            "Covers Vocabulary, Grammar Agreement, and Reading Comprehension.",
            "Marking Scheme: +1 for correct, -0.33 penalty for incorrect answers.",
            "Designed for complete screen-reader and voice navigation support.",
        ],
        "accessibilityHighlights": {
            "keyboard": "Full keyboard navigation supported.",
            "screenReader": "ARIA-live announcements on option selection.",
            "audio": "Audio description support for prompts.",
            "visual": "High contrast AAA presets.",
        },
        "sections": [
            {
                "id": "sec-eng-vocab",
                "name": "Vocabulary & Word Power",
                "code": "VOCAB",
                "description": "Antonyms, synonyms, and contextual vocabulary.",
                "totalQuestions": 2,
                "questions": [
                    {
                        "id": "eng-m-01",
                        "sectionId": "sec-eng-vocab",
                        "questionNumber": 1,
                        "text": "Choose the word that is most nearly opposite in meaning to 'CANDID':",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "options": [
                            {"id": "A", "label": "A", "text": "Outspoken"},
                            {"id": "B", "label": "B", "text": "Secretive"},
                            {"id": "C", "label": "C", "text": "Blunt"},
                            {"id": "D", "label": "D", "text": "Sincere"},
                        ],
                        "correctOptionIds": ["B"],
                        "explanation": "'Candid' means open and frank. Its direct antonym is 'secretive'.",
                        "audioText": "Question 1. Choose the word that is most nearly opposite in meaning to CANDID.",
                    },
                    {
                        "id": "eng-m-02",
                        "sectionId": "sec-eng-vocab",
                        "questionNumber": 2,
                        "text": "Select the word that is most similar in meaning to 'METICULOUS':",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "options": [
                            {"id": "A", "label": "A", "text": "Careless"},
                            {"id": "B", "label": "B", "text": "Diligent"},
                            {"id": "C", "label": "C", "text": "Casual"},
                            {"id": "D", "label": "D", "text": "Hasty"},
                        ],
                        "correctOptionIds": ["B"],
                        "explanation": "'Meticulous' means showing great attention to detail; very careful and precise (diligent).",
                        "audioText": "Question 2. Select the word that is most similar in meaning to METICULOUS.",
                    },
                ],
            },
            {
                "id": "sec-eng-gram",
                "name": "Grammar & Sentence Correction",
                "code": "GRAM",
                "description": "Subject-verb agreement and sentence rectification.",
                "totalQuestions": 2,
                "questions": [
                    {
                        "id": "eng-m-03",
                        "sectionId": "sec-eng-gram",
                        "questionNumber": 3,
                        "text": "Select the option that correctly rectifies the grammatical error: 'Neither the manager nor the employees was present at the briefing.'",
                        "type": "single_choice",
                        "difficulty": "medium",
                        "options": [
                            {"id": "A", "label": "A", "text": "Neither the manager nor the employees were present at the briefing."},
                            {"id": "B", "label": "B", "text": "Neither the manager or the employees was present at the briefing."},
                            {"id": "C", "label": "C", "text": "Neither the manager nor the employee was present at the briefing."},
                            {"id": "D", "label": "D", "text": "No correction required."},
                        ],
                        "correctOptionIds": ["A"],
                        "explanation": "Subject closest to the verb ('employees') is plural, so 'were present' is required.",
                        "audioText": "Question 3. Select the option that correctly rectifies the grammatical error.",
                    },
                    {
                        "id": "eng-m-04",
                        "sectionId": "sec-eng-gram",
                        "questionNumber": 4,
                        "text": "Fill in the blank with the grammatically correct auxiliary verb: 'One of the cadets ___ chosen for the special honor guard.'",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "options": [
                            {"id": "A", "label": "A", "text": "was"},
                            {"id": "B", "label": "B", "text": "were"},
                            {"id": "C", "label": "C", "text": "are"},
                            {"id": "D", "label": "D", "text": "have been"},
                        ],
                        "correctOptionIds": ["A"],
                        "explanation": "The subject is 'One', which is singular, demanding the singular verb 'was'.",
                        "audioText": "Question 4. Fill in the blank: One of the cadets blank chosen for the special honor guard.",
                    },
                ],
            },
            {
                "id": "sec-eng-rc",
                "name": "Reading & Idiomatic Expressions",
                "code": "RC",
                "description": "Discourse markers and idiomatic phrases.",
                "totalQuestions": 2,
                "questions": [
                    {
                        "id": "eng-m-05",
                        "sectionId": "sec-eng-rc",
                        "questionNumber": 5,
                        "text": "When an author uses the transitional phrase 'on the contrary', what argumentative direction is signaled?",
                        "type": "single_choice",
                        "difficulty": "medium",
                        "options": [
                            {"id": "A", "label": "A", "text": "Reinforcement of a previously stated premise"},
                            {"id": "B", "label": "B", "text": "An emphatic reversal or counter-argument"},
                            {"id": "C", "label": "C", "text": "A sequential chronological timeline"},
                            {"id": "D", "label": "D", "text": "A summary conclusion"},
                        ],
                        "correctOptionIds": ["B"],
                        "explanation": "'On the contrary' signals a sharp contrast or contradiction to a preceding statement.",
                        "audioText": "Question 5. When an author uses the phrase on the contrary, what argumentative direction is signaled?",
                    },
                    {
                        "id": "eng-m-06",
                        "sectionId": "sec-eng-rc",
                        "questionNumber": 6,
                        "text": "What is the meaning of the idiom 'To burn the candle at both ends'?",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "options": [
                            {"id": "A", "label": "A", "text": "To work excessively hard without adequate rest"},
                            {"id": "B", "label": "B", "text": "To waste resources foolishly"},
                            {"id": "C", "label": "C", "text": "To remain undecided"},
                            {"id": "D", "label": "D", "text": "To celebrate enthusiastically"},
                        ],
                        "correctOptionIds": ["A"],
                        "explanation": "'To burn the candle at both ends' means exhausting one's physical energies by working early in the morning until late at night.",
                        "audioText": "Question 6. What is the meaning of the idiom to burn the candle at both ends?",
                    },
                ],
            },
        ],
    },
    {
        "id": "mock-gk-01",
        "title": "General Knowledge & Defense Mock Test",
        "examName": "CDS (Combined Defence Services)",
        "examCode": "CDS-GK",
        "description": "Subject-wise mock covering Indian Polity & Constitution, Modern History, General Science, and Defense Affairs.",
        "totalQuestions": 6,
        "durationMinutes": 30,
        "difficulty": "easy",
        "status": "not_started",
        "isRecommended": True,
        "markingScheme": {
            "correctMarks": 1.0,
            "incorrectPenalty": 0.33,
            "unansweredMarks": 0.0,
        },
        "instructionsSummary": [
            "Focused assessment on Indian Polity, Constitution, General Science, and Defense.",
            "Negative marking: +1 for correct answers, -0.33 for incorrect attempts.",
            "Unanswered questions carry zero penalty.",
        ],
        "accessibilityHighlights": {
            "keyboard": "Standard navigation shortcuts active.",
            "screenReader": "Accessible tables and question options.",
            "audio": "Question audio reader enabled.",
            "visual": "Large font and high contrast modes available.",
        },
        "sections": [
            {
                "id": "sec-gk-pol",
                "name": "Indian Polity & Constitution",
                "code": "POL",
                "description": "Fundamental Rights and Directive Principles.",
                "totalQuestions": 2,
                "questions": [
                    {
                        "id": "gk-m-01",
                        "sectionId": "sec-gk-pol",
                        "questionNumber": 1,
                        "text": "Which Article of the Indian Constitution guarantees the Right to Equality before Law?",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "options": [
                            {"id": "A", "label": "A", "text": "Article 14"},
                            {"id": "B", "label": "B", "text": "Article 19"},
                            {"id": "C", "label": "C", "text": "Article 21"},
                            {"id": "D", "label": "D", "text": "Article 32"},
                        ],
                        "correctOptionIds": ["A"],
                        "explanation": "Article 14 guarantees equality before law and equal protection of the laws.",
                        "audioText": "Question 1. Which Article of the Indian Constitution guarantees the Right to Equality before Law?",
                    },
                    {
                        "id": "gk-m-02",
                        "sectionId": "sec-gk-pol",
                        "questionNumber": 2,
                        "text": "The Directive Principles of State Policy in the Indian Constitution were borrowed from which country?",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "options": [
                            {"id": "A", "label": "A", "text": "United Kingdom"},
                            {"id": "B", "label": "B", "text": "Ireland"},
                            {"id": "C", "label": "C", "text": "USA"},
                            {"id": "D", "label": "D", "text": "Canada"},
                        ],
                        "correctOptionIds": ["B"],
                        "explanation": "The Directive Principles of State Policy (Part IV) were borrowed from the Constitution of Ireland.",
                        "audioText": "Question 2. The Directive Principles of State Policy in the Indian Constitution were borrowed from which country?",
                    },
                ],
            },
            {
                "id": "sec-gk-sci",
                "name": "General Science & Technology",
                "code": "SCI",
                "description": "Environmental science and indigenous aerospace.",
                "totalQuestions": 2,
                "questions": [
                    {
                        "id": "gk-m-03",
                        "sectionId": "sec-gk-sci",
                        "questionNumber": 3,
                        "text": "Which gas is primarily responsible for the greenhouse effect on Earth?",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "options": [
                            {"id": "A", "label": "A", "text": "Carbon Dioxide"},
                            {"id": "B", "label": "B", "text": "Nitrogen"},
                            {"id": "C", "label": "C", "text": "Oxygen"},
                            {"id": "D", "label": "D", "text": "Argon"},
                        ],
                        "correctOptionIds": ["A"],
                        "explanation": "Carbon dioxide is the primary greenhouse gas contributing to global temperature trapping.",
                        "audioText": "Question 3. Which gas is primarily responsible for the greenhouse effect on Earth?",
                    },
                    {
                        "id": "gk-m-04",
                        "sectionId": "sec-gk-sci",
                        "questionNumber": 4,
                        "text": "What is the primary operational fighter aircraft of the Indian Air Force developed indigenously in India?",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "options": [
                            {"id": "A", "label": "A", "text": "LCA Tejas"},
                            {"id": "B", "label": "B", "text": "Sukhoi Su-30MKI"},
                            {"id": "C", "label": "C", "text": "Mirage 2000"},
                            {"id": "D", "label": "D", "text": "Rafale"},
                        ],
                        "correctOptionIds": ["A"],
                        "explanation": "The Light Combat Aircraft (LCA) Tejas is an indigenous 4.5 generation fighter developed by ADA and HAL.",
                        "audioText": "Question 4. What is the primary operational combat aircraft developed indigenously in India?",
                    },
                ],
            },
            {
                "id": "sec-gk-def",
                "name": "Defense & Modern History",
                "code": "DEF",
                "description": "Armed forces exercises and national historical leaders.",
                "totalQuestions": 2,
                "questions": [
                    {
                        "id": "gk-m-05",
                        "sectionId": "sec-gk-def",
                        "questionNumber": 5,
                        "text": "The bilateral joint military exercise 'MITRA SHAKTI' is conducted between India and which country?",
                        "type": "single_choice",
                        "difficulty": "medium",
                        "options": [
                            {"id": "A", "label": "A", "text": "Nepal"},
                            {"id": "B", "label": "B", "text": "Sri Lanka"},
                            {"id": "C", "label": "C", "text": "Bangladesh"},
                            {"id": "D", "label": "D", "text": "Maldives"},
                        ],
                        "correctOptionIds": ["B"],
                        "explanation": "Exercise Mitra Shakti is conducted between Indian Army and Sri Lanka Army.",
                        "audioText": "Question 5. The bilateral military exercise MITRA SHAKTI is conducted between India and which country?",
                    },
                    {
                        "id": "gk-m-06",
                        "sectionId": "sec-gk-def",
                        "questionNumber": 6,
                        "text": "Who revitalized and led the Indian National Army (Azad Hind Fauj) with the historic call 'Give me blood, and I shall give you freedom'?",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "options": [
                            {"id": "A", "label": "A", "text": "Netaji Subhas Chandra Bose"},
                            {"id": "B", "label": "B", "text": "Bhagat Singh"},
                            {"id": "C", "label": "C", "text": "Chandrashekhar Azad"},
                            {"id": "D", "label": "D", "text": "Lala Lajpat Rai"},
                        ],
                        "correctOptionIds": ["A"],
                        "explanation": "Netaji Subhas Chandra Bose took supreme command of the INA in 1943 in Singapore.",
                        "audioText": "Question 6. Who revitalized and led the Indian National Army Azad Hind Fauj?",
                    },
                ],
            },
        ],
    },
    {
        "id": "mock-reas-01",
        "title": "Reasoning Ability & Mental Aptitude Mock Test",
        "examName": "CDS (Combined Defence Services)",
        "examCode": "CDS-REAS",
        "description": "Subject-wise mock testing Deductive Logic, Coding-Decoding, Number Series, and Direction Sense.",
        "totalQuestions": 6,
        "durationMinutes": 30,
        "difficulty": "medium",
        "status": "not_started",
        "isRecommended": True,
        "markingScheme": {
            "correctMarks": 1.0,
            "incorrectPenalty": 0.33,
            "unansweredMarks": 0.0,
        },
        "instructionsSummary": [
            "Covers Deductive Logic, Coding-Decoding, and Number Sequences.",
            "Marking Scheme: +1 for correct, -0.33 penalty for incorrect answers.",
            "Accessible navigation supported across all question cards.",
        ],
        "accessibilityHighlights": {
            "keyboard": "Full keyboard navigation supported.",
            "screenReader": "Screen reader compatible formatting.",
            "audio": "Audio description support for prompts.",
            "visual": "High contrast and scalable typography supported.",
        },
        "sections": [
            {
                "id": "sec-reas-code",
                "name": "Coding & Decoding",
                "code": "CODE",
                "description": "Letter shifts and alphabet numerical ranks.",
                "totalQuestions": 2,
                "questions": [
                    {
                        "id": "reas-m-01",
                        "sectionId": "sec-reas-code",
                        "questionNumber": 1,
                        "text": "In a certain code language, CAT is coded as 24 and DOG is coded as 26. What is the code for PIG?",
                        "type": "single_choice",
                        "difficulty": "medium",
                        "options": [
                            {"id": "A", "label": "A", "text": "32"},
                            {"id": "B", "label": "B", "text": "30"},
                            {"id": "C", "label": "C", "text": "28"},
                            {"id": "D", "label": "D", "text": "34"},
                        ],
                        "correctOptionIds": ["A"],
                        "explanation": "Sum of alphabetical ranks: P(16) + I(9) + G(7) = 32.",
                        "audioText": "Question 1. In a certain code language, CAT is coded as 24 and DOG is coded as 26. What is the code for PIG?",
                    },
                    {
                        "id": "reas-m-02",
                        "sectionId": "sec-reas-code",
                        "questionNumber": 2,
                        "text": "If 'DELHI' is coded as 'EDMIJ', how is 'MUMBAI' coded following the exact same letter shift rule?",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "options": [
                            {"id": "A", "label": "A", "text": "NVNCBJ"},
                            {"id": "B", "label": "B", "text": "NVMCBJ"},
                            {"id": "C", "label": "C", "text": "LTLAZH"},
                            {"id": "D", "label": "D", "text": "OWNCDK"},
                        ],
                        "correctOptionIds": ["A"],
                        "explanation": "Each letter is shifted forward by 1: M(+1)=N, U(+1)=V, M(+1)=N, B(+1)=C, A(+1)=B, I(+1)=J => NVNCBJ.",
                        "audioText": "Question 2. If DELHI is coded as EDMIJ, how is MUMBAI coded?",
                    },
                ],
            },
            {
                "id": "sec-reas-seq",
                "name": "Number & Alphabet Sequences",
                "code": "SEQ",
                "description": "Progressions, geometric series, and alphabet series.",
                "totalQuestions": 2,
                "questions": [
                    {
                        "id": "reas-m-03",
                        "sectionId": "sec-reas-seq",
                        "questionNumber": 3,
                        "text": "Find the missing number in the sequence: 3, 7, 15, 31, 63, ___",
                        "type": "single_choice",
                        "difficulty": "medium",
                        "options": [
                            {"id": "A", "label": "A", "text": "95"},
                            {"id": "B", "label": "B", "text": "127"},
                            {"id": "C", "label": "C", "text": "125"},
                            {"id": "D", "label": "D", "text": "110"},
                        ],
                        "correctOptionIds": ["B"],
                        "explanation": "Each term is obtained by: (Previous * 2) + 1. So 63 * 2 + 1 = 127.",
                        "audioText": "Question 3. Find the missing number in the sequence: 3, 7, 15, 31, 63, blank.",
                    },
                    {
                        "id": "reas-m-04",
                        "sectionId": "sec-reas-seq",
                        "questionNumber": 4,
                        "text": "What is the next letter in the increasing gap sequence: B, D, G, K, P, ___?",
                        "type": "single_choice",
                        "difficulty": "medium",
                        "options": [
                            {"id": "A", "label": "A", "text": "S"},
                            {"id": "B", "label": "B", "text": "U"},
                            {"id": "C", "label": "C", "text": "V"},
                            {"id": "D", "label": "D", "text": "W"},
                        ],
                        "correctOptionIds": ["C"],
                        "explanation": "The alphabetical ranks increase by consecutive numbers: B(2)+2=D(4), D(4)+3=G(7), G(7)+4=K(11), K(11)+5=P(16), P(16)+6=V(22). Hence V.",
                        "audioText": "Question 4. What is the next letter in the increasing gap sequence: B, D, G, K, P, blank?",
                    },
                ],
            },
            {
                "id": "sec-reas-logic",
                "name": "Analogy & Direction Sense",
                "code": "LOGIC",
                "description": "Functional analogies and spatial distance problems.",
                "totalQuestions": 2,
                "questions": [
                    {
                        "id": "reas-m-05",
                        "sectionId": "sec-reas-logic",
                        "questionNumber": 5,
                        "text": "Complete the analogy: Doctor is to Hospital as Teacher is to:",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "options": [
                            {"id": "A", "label": "A", "text": "Classroom"},
                            {"id": "B", "label": "B", "text": "School"},
                            {"id": "C", "label": "C", "text": "Student"},
                            {"id": "D", "label": "D", "text": "Library"},
                        ],
                        "correctOptionIds": ["B"],
                        "explanation": "A doctor's primary workplace institution is a hospital; a teacher's primary workplace institution is a school.",
                        "audioText": "Question 5. Doctor is to Hospital as Teacher is to what?",
                    },
                    {
                        "id": "reas-m-06",
                        "sectionId": "sec-reas-logic",
                        "questionNumber": 6,
                        "text": "A candidate walks 4 km North, then turns right and walks 3 km East. What is the straight-line distance from the starting point?",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "formula": {
                            "visualText": "Distance = √(4² + 3²) = √(16 + 9) = √25 = 5 km",
                            "accessibleText": "Distance equals square root of 4 squared plus 3 squared equals square root of 25 equals 5 kilometers",
                        },
                        "options": [
                            {"id": "A", "label": "A", "text": "7 km"},
                            {"id": "B", "label": "B", "text": "5 km"},
                            {"id": "C", "label": "C", "text": "1 km"},
                            {"id": "D", "label": "D", "text": "6 km"},
                        ],
                        "correctOptionIds": ["B"],
                        "explanation": "Applying Pythagoras theorem: Hypotenuse = √(4² + 3²) = √(16 + 9) = √25 = 5 km.",
                        "audioText": "Question 6. A candidate walks 4 km North, then turns right and walks 3 km East. What is the straight-line distance from the starting point?",
                    },
                ],
            },
        ],
    },
    {
        "id": "cds-gk-assessment-02",
        "title": "General Knowledge & Current Affairs Drill",
        "examName": "CDS (Combined Defence Services)",
        "examCode": "CDS-2026-GK",
        "description": "Focused assessment on Indian Polity, Constitution, Physical Geography, and General Science.",
        "totalQuestions": 4,
        "durationMinutes": 30,
        "difficulty": "easy",
        "status": "not_started",
        "isRecommended": False,
        "markingScheme": {
            "correctMarks": 1.0,
            "incorrectPenalty": 0.33,
            "unansweredMarks": 0.0,
        },
        "instructionsSummary": [
            "This is a focused drill covering Indian Constitution, Geography, and Defense topics.",
            "Negative marking: +1 for correct answers, -0.33 for incorrect attempts.",
            "Unanswered questions carry zero penalty.",
        ],
        "accessibilityHighlights": {
            "keyboard": "Full keyboard navigation supported.",
            "screenReader": "Fully screen-reader compatible with accessible question structure.",
            "audio": "Audio description support for prompts.",
            "visual": "High contrast and scalable typography supported.",
        },
        "sections": [
            {
                "id": "sec-polity",
                "name": "Indian Polity & Constitution",
                "code": "POL",
                "description": "Fundamental Rights, Directive Principles, and Governance.",
                "totalQuestions": 2,
                "questions": [
                    {
                        "id": "gk-q-1",
                        "sectionId": "sec-polity",
                        "questionNumber": 1,
                        "text": "Which Article of the Indian Constitution guarantees the Right to Equality before Law?",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "options": [
                            {"id": "A", "label": "A", "text": "Article 14"},
                            {"id": "B", "label": "B", "text": "Article 19"},
                            {"id": "C", "label": "C", "text": "Article 21"},
                            {"id": "D", "label": "D", "text": "Article 32"},
                        ],
                        "correctOptionIds": ["A"],
                        "explanation": "Article 14 guarantees equality before law and equal protection of the laws.",
                        "audioText": "Question 1. Which Article of the Indian Constitution guarantees the Right to Equality before Law?",
                    },
                    {
                        "id": "gk-q-2",
                        "sectionId": "sec-polity",
                        "questionNumber": 2,
                        "text": "The Directive Principles of State Policy in the Indian Constitution were borrowed from which country?",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "options": [
                            {"id": "A", "label": "A", "text": "United Kingdom"},
                            {"id": "B", "label": "B", "text": "Ireland"},
                            {"id": "C", "label": "C", "text": "USA"},
                            {"id": "D", "label": "D", "text": "Canada"},
                        ],
                        "correctOptionIds": ["B"],
                        "explanation": "The Directive Principles of State Policy were borrowed from the Constitution of Ireland.",
                        "audioText": "Question 2. The Directive Principles of State Policy in the Indian Constitution were borrowed from which country?",
                    },
                ],
            },
            {
                "id": "sec-science",
                "name": "General Science & Defense",
                "code": "SCI",
                "description": "Physics, Chemistry, Biology, and Defense preparedness.",
                "totalQuestions": 2,
                "questions": [
                    {
                        "id": "gk-q-3",
                        "sectionId": "sec-science",
                        "questionNumber": 3,
                        "text": "Which gas is primarily responsible for the greenhouse effect on Earth?",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "options": [
                            {"id": "A", "label": "A", "text": "Carbon Dioxide"},
                            {"id": "B", "label": "B", "text": "Nitrogen"},
                            {"id": "C", "label": "C", "text": "Oxygen"},
                            {"id": "D", "label": "D", "text": "Argon"},
                        ],
                        "correctOptionIds": ["A"],
                        "explanation": "Carbon dioxide is the primary greenhouse gas contributing to the greenhouse effect.",
                        "audioText": "Question 3. Which gas is primarily responsible for the greenhouse effect on Earth?",
                    },
                    {
                        "id": "gk-q-4",
                        "sectionId": "sec-science",
                        "questionNumber": 4,
                        "text": "What is the primary operational combat aircraft of the Indian Air Force developed indigenously in India?",
                        "type": "single_choice",
                        "difficulty": "easy",
                        "options": [
                            {"id": "A", "label": "A", "text": "LCA Tejas"},
                            {"id": "B", "label": "B", "text": "Sukhoi Su-30MKI"},
                            {"id": "C", "label": "C", "text": "Mirage 2000"},
                            {"id": "D", "label": "D", "text": "Rafale"},
                        ],
                        "correctOptionIds": ["A"],
                        "explanation": "The Light Combat Aircraft (LCA) Tejas is an indigenous 4.5 generation fighter aircraft.",
                        "audioText": "Question 4. What is the primary operational combat aircraft developed indigenously in India?",
                    },
                ],
            },
        ],
    },
]
